# Generated by Django 3.1.1 on 2020-09-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bauthors', '0004_auto_20200911_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Read more...', max_length=255),
        ),
    ]
